#ifndef BLAZE_CONFIG_HPP
#define BLAZE_CONFIG_HPP

#define INCLUDE_GMSH 0
#define VERBOSE 0
#define VERBOSE_SLN 1
#define VERBOSE_STIFFNESSES 0
#define VERBOSE_NLB 1
#define LF_VERBOSE 1
#define ELEMENT_VERBOSE 1
#define WITH_MPI
#endif
